# server {

#     listen 80;

#     root /var/www/public;

#     index index.php index.html;

#     server_tokens off;

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {

#         fastcgi_pass app:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;

#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_read_timeout 300;
#     }

#     location ~ /\. {
#         deny all;
#     }

#     location ~* \.(env|log|ini)$ {
#         deny all;
#     }
# }



server {

    listen 80;

    root /var/www/public;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {

        fastcgi_pass app:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }


    location ~ /\. {
        deny all;
    }

    location ~* \.(env|log|ini)$ {
        deny all;
    }
}